### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by antialias** [webpack/memory-fs#10]
This has not been published to npm in a while. I'm interested in the fixes to exception handling for compatibility with [`mkdirp`](https://www.npmjs.com/package/mkdirp). Currently I've got a link to this github repo in my `package.json`, but I'd rather use a semver.

**Comment by guncha** [comment]
Agreed, that would be real nice! All it takes is a quick commit and `npm publish`. Otherwise, the docs on webpack.github.io are wrong as the example using memory-fs is broken.

**Comment by jprichardson** [comment]
:+1:
