### ISSUE TITLE
What does normalize do?

### ISSUE THREAD

**Issue by callumlocke** [webpack/memory-fs#11]
Hi! I'm really curious about your [normalize() function](https://github.com/webpack/memory-fs/blob/master/lib/normalize.js).

At first glance it like it handles a lot of interesting cases, but I tested it on a bunch of different strings and it seemed to work exactly like [path.normalize](https://nodejs.org/api/path.html#path_path_normalize_p). What am I missing?

**Comment by sokra** [comment]
this normalize detects if the passed value is unix or windows. the `path.normalize` changes it behavior depending on which os you are.
