### ISSUE TITLE
Revert 0.3.0

### ISSUE THREAD

**Issue by appsforartists** [webpack/memory-fs#13]
0.3.0 started requiring errno, which doesn't work in strict mode:

https://github.com/rvagg/node-errno/pull/13

**Comment by gajus** [comment]
@appsforartists Please provide more information.

I don't understand the issue or what needs to be reverted to what.

**Comment by gajus** [comment]
Closing this as the original author did not follow up.

I will re-open this issue if there is a follow up explaining the issue.
