### ISSUE TITLE
Use this project with Webpack?

### ISSUE THREAD

**Issue by christianalfoni** [webpack/memory-fs#16]
Is it possible to make webpack use an in memory file system rather than the normal file system? I need to run webpack completely in memory. all files are already in memory and I want to start a webpack process.

Also react to changes to these files to trigger a rebundle.

Just wondering if it is even possible? And if so, with this project?

**Comment by chrisblossom** [comment]
@christianalfoni Yes you can, see [webpack-dev-middleware/blob/master/middleware.js#L33](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L33) for an example how to use it.

**Comment by christianalfoni** [comment]
Fantastic, thanks for pointing me in the right direction :-)

**Comment by christianalfoni** [comment]
Though, hm, this seems to be only the output as "in memory"? I also need the input to webpack to me from "in memory" fs. Or am I misunderstanding the code maybe?

**Comment by chrisblossom** [comment]
@christianalfoni I am not sure what you are trying to do, sorry.

**Comment by christianalfoni** [comment]
Okay, sorry, let me explain a bit better with an example :-)

1. I have an online IDE with multiple files in a file structure
2. I want to pass these files to the server. Just a string and a virtual filepath for each file
3. I want to add these files to an "in memory file system"
4. I want webpack to read from this "in memory file system" and bundle the files to an "in memory" output (which the middleware already does)
5. This bundled output is loaded by a preview window on the client

Since the webpack compiler watches the "in memory filesystem" any file changes I pass to the server will make the compiler react to it and do superfast rebundling, where the preview window on the client will again grab it.

This makes it possible for the online IDE to write applications using webpack, loaders, node packages etc.

**Comment by christianalfoni** [comment]
I found a way to solve it! Thanks for helping out :-)

**Comment by chrisblossom** [comment]
@christianalfoni It would be great for you to share your solution for the next person with the same issue.

**Comment by christianalfoni** [comment]
Ah, yes, sorry. Its currently in "pre pre alpha", but here it is: https://github.com/christianalfoni/webpack-bin. Also running on Heroku now, webpackbin.herokuapp.com
