### ISSUE TITLE
"Statting" a file under a non-existant directory causes MemoryFileSystem.statSync to throw an error

### ISSUE THREAD

**Issue by nathanhinish** [webpack/memory-fs#19]
MemoryFileSystem.priotoype.meta loops through 0...n-1 entries in the split file path. Suppose, _/path/to/existing/files_ exists but _/path/to/existing/files/plus_ does not. Then, sending _/path/to/existing/files/plus/extra_ causes the _meta_ method to return **null**. This causes an issue in the conditional inside statSync(). When isDir() is called, it tests the type of the incoming object. But if that object is **null**, typeof evaluates to "object", which I believe is unintended.

I believe the fix for this is to return **undefined** inside MemoryFileSystem.priotoype.meta instead of **null**.

**Comment by nathanhinish** [comment]
Place this somewhere in your project to correct the error for now...

`const MemoryFileSystem = require('memory-fs')

// Currently, there's a bug in MemoryFileSystem
// that causes an error when a file in a
// non-existent directory is passed in to stat()
const memMeta = MemoryFileSystem.prototype.meta

MemoryFileSystem.prototype.meta = function meta(_path) {
  const result = memMeta.bind(this, _path)
  if (result === null) {
    result = undefined
  }
  return result
}`

**Comment by sokra** [comment]
yep, that's correct. Thanks for investigating. Do you want to send a PR?
