### ISSUE TITLE
Relative requests not normalized correctly using absolute paths in windows

### ISSUE THREAD

**Issue by ntrpy** [webpack/memory-fs#20]
Trying to join paths of kind 'C:/your/path/here' with relative requests like './../../my/module/path' result in 'C:/your/path/here\my\module\path' instead of 'C:/your\my\module\path'.

This is due to converting slashes in the request, but not in the path when invoking join.

**Comment by gajus** [comment]
> instead of 'C:/your\my\module\path'.

I think it should be:

```
C:\your\my\module\path
```
