### ISSUE TITLE
Async functions should call the callbacks asynchronously

### ISSUE THREAD

**Issue by isiahmeadows** [webpack/memory-fs#22]
Unlike the real Node API, the async variants [have their callbacks called synchronously](https://github.com/webpack/memory-fs/blob/dfc75be36e0322f533e1b2ba97dfe53021016e19/lib/MemoryFileSystem.js#L276-L315). This is really odd, and can lead to bugs for people using this as a mock, especially if they're calling the functions asynchronously.

Could these callbacks be wrapped in a `setImmediate`, so they are a) actually called async in the first place and b) scheduled as macrotasks like in Node?

**Comment by sokra** [comment]
yep, callbacks should be invoked with `process.nextTick`

**Comment by isiahmeadows** [comment]
Shouldn't they be deferred with `setTimeout`? I/O callbacks are scheduled
as macrotasks, not microtasks.

**Comment by sokra** [comment]
We are not emulating a filesystem. So it's here just async for the APIs sake.

**Comment by isiahmeadows** [comment]
I know it's not a full file system emulation. I'm just pointing out
semantics (people might rely on the macrotask semantics, in which
scheduling a microtask would break their code).

**Comment by sokra** [comment]
Could be an issue... You are right.

Than it might be better to use `setImmediate` instead. @gajus
