### ISSUE TITLE
DEPRECATED? memfs not compatible with this library.

### ISSUE THREAD

**Issue by vipcxj** [webpack/memory-fs#72]
I try to use memfs to replace this library, and found some problem
```ts
import { fs } from 'memfs'
compiler.outputFileSystem = fs // TS2741: Property 'join' is missing in type 'IFs' but required in type 'OutputFileSystem'.
```

**Comment by thirteen-io** [comment]
Related to: https://github.com/webpack/webpack-dev-middleware/pull/370 and #67.

**Comment by paullaffitte** [comment]
I cannot use memfs for `compiler.inputFileSystem`.

**Comment by tcstory** [comment]
> I cannot use memfs for `compiler.inputFileSystem`.

same problem
